### PR TITLE
Offchain workers sending requests upon certain actions

### PR DESCRIPTION
**Pull request by jimmychu0807**
@stiiifff  This is the ocw on pallet-product-tracking. I will fix the formatting (which cause the CI failure) later today/tmr.

Thanks

### CODE REVIEW

**Comment by stiiifff** [comment]
@jimmychu0807 I feel like the use of alt_serde for custom serialization adds a layer of complexity to the pallet. Maybe we could go something simpler (w/o custom serde) first (simple POST w/o a payload), and in // figure out how to serialize the data w/o custom serde, and add it at a later point.

**Comment by jimmychu0807** [comment]
Instead of alt_serde serialization, we can do a `to_string()` to the OcwTask, and convert the object to a bunch of csv values, like, `<id>, <event_type>, <shipment_id>, ...`. But there are some nested data structure inside, such as `readings`, will be simplified or skipped.

Actually the current method of doing serialization is the one implemented/used by Substrate offchain-worker team led by Tomek. `alt_serde` is exactly the same as `serde` but included in with a different name. This is because `serde` is compiled with `std` feature, and it cannot be used as `no-std` at the same time when compiling the runtime, due to rust compiler restriction. So we include it in using another name. The `serde_json` is customized/enhanced by another teammate Xanewok to do json serialization in `no_std` environment, I believe he has made a PR to the upstream serde_json package and is soon to be (or already) merged.

**Comment by jimmychu0807** [comment]
Another complexed part is that you see I `impl Serialize for <type>` for multiple types. I believe this can be simplified, but I don't know how to solve the following problem as posted in Substrate Technical Public channel.

> I am working on a pallet that need to serialize an object to JSON. The object type is OcwTask<T::AccountId, T::Moment>.
> When I compile, compiler complains the trait alt_serde::ser::Serialize is not implemented for <T as pallet_timestamp::Trait>::Moment, and also for the <T as frame_system::Trait>::AccountId.
>
> My problem is that I cannot simply add impl Serialize for <T as frame_system::Trait>::AccountId {...} because first my pallet don't own the type, and second T is not existed outside of the macro.
>
> What can I do to make serde serialization work for my type?
>
> Here is the code on serialization:
> https://github.com/stiiifff/pallet-product-tracking/commit/d88ad27d29d04107fbd9a7f99c3262b7d07a729b/src/lib.rs#L369-L374
>
> This is the object type definition:
> https://github.com/stiiifff/pallet-product-tracking/commit/d88ad27d29d04107fbd9a7f99c3262b7d07a729b/src/lib.rs#L158-L161

**Comment by jimmychu0807** [comment]
Closing this to be replaced by #8

**Pull request closed without merging**
