### PR TITLE
Some simplification

### PR DESCRIPTION
**Pull request by jimmychu0807**
@stiiifff I have a second look at the branch, and have this thought of simplification, mainly:

- added `ShippingOperation::Scan` - which is pretty much like sensor reading before.
- added appropriate match arm
- I wonder why can't we do `track_shipment` and `monitor_shipment` together? Looking at their logic, they look similar
- minor english preposition update

I like the `ShippingEventBuilder` to build up shipping event 😉 . I would say overall it is better to do the refactor now.

I haven't updated the test yet, but want to get your quick thought on simplifying two functions into one.

### CODE REVIEW

**Comment by stiiifff** [comment]
@jimmychu0807 All good ! About merging `track_shipment` and `monitor_shipment`, they do look awfully similar, but my thinking was along those lines:
- `track_shipment` would be called by field service apps from a user-initiated action, like scanning the shipment at customs or in a warehouse (-> This would typically be called by the sample Android app).
- `monitor_shipment` whould be called by IoT devices / gateways to report transportation conditions (-> we can later expand the sample with a node running on a Raspberry Pi).

Separating the two to cater for different use cases therefore made sense e.g. allow to apply different strategies re. access control.
But I may be overthinking all this 😂 Maybe @gautamdhameja @riusricardo can give us their input.

**Comment by stiiifff** [comment]
> I would say overall it is better to do the refactor now.

Yes, I thought it was best to go through the hassles of changing stuff now rather than later, thanks for putting up with it 😉

**Comment by jimmychu0807** [comment]
yea, I see the reasoning that in one use case it is a logistic staff scanning items, and another one is like sensor scanning the environment reading. But on further thinking about it, I realize though the use cases are different, the logic is similar. Because, for sensor scanning environment reading, we still need to keep track of the timestamp, location, associating the reading with shipment (thus the `shipment_id field`). It also implicitly show where the shipment has reached by recording the `location` field.

But this is your repo, you have the final say on this. See if you want to merge this branch to your draft PR, uncomment the `monitor_shipment` function, and then merge it to `master`. Then we can move forward.

**Comment by jimmychu0807** [comment]
@stiiifff with the latest update:
- refactor all types to `types.rs` and builders to `builders.rs`, making the pallet logic easier to follow.
- make all tests pass.
- uncomment `fn monitor_shipment`

If you are happy with this, please merge to your draft PR and then merge to master. I will rework the ocw functionality on top of this.

**Review by riusricardo — COMMENTED** [review]
I see the reasoning behind two different functions. I also agree with jimmy that it can be merged. 
Both write to the same storage variable  with a slightly different behavior. We could merge them and use another parameter as a flag to indicate the type, if it's from an IOT device or from a scanner and use a conditional flow. Could be a boolean flag if we only see this 2 cases or a more open option as an enum type and using a conditional match.

**Review by stiiifff — APPROVED** [review]

**Pull request merged**
